services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      SA_PASSWORD: "P@ssw0rd1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./mssql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  sqlserver-data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
